language: java
install: true

os: linux
dist: trusty
jdk: oraclejdk8

jobs:
  include:
    - stage: build
      script: "./gradlew build"
    - stage: deploy_release
      script: "./gradlew bintrayUpload"
      if: tag IS present
